// <auto-generated />
namespace QLDeTai.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatelan4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatelan4));
        
        string IMigrationMetadata.Id
        {
            get { return "202312060800501_updatelan4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
